version: "2"
linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - decorder
    - gocritic
    - gocyclo
    - gosec
    - zerologlint
    - testifylint
    - paralleltest
    - copyloopvar
    - godox
  settings:
    godox:
      keywords:
      - "DEBUG"
      - "TODO"
