[tools]
go = "1.27.0"
golangci-lint = "2.13.1"
goreleaser = "2.17.1"
air = "1.67.4"

[tasks.goreleaser]
run = "goreleaser release --clean --snapshot"

[tasks.lint]
run = "golangci-lint run ./... --fix"

[tasks.test]
run = "go tool gotestsum -- -timeout 30s -cover ./..."

[tasks.test-race]
run = "go tool gotestsum -- -timeout 2m -race ./..."

[tasks.bench]
run = "go test -bench=. -benchmem -run='^$' ./... -cpu=2,4,8"

[tasks.mcp]
run = "go run . mcp --github-token $GITHUB_TOKEN"

[tasks.mocks]
run = "go generate ./..."

[tasks.hooks]
description = "Install lefthook git hooks"
run = "lefthook install"

[tasks.install]
description = "Install latest build to path"
run = "go install ./..."

[tasks.dev]
description = "Run air for live-reloading development"
run = "air"
