// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mcp

import (
	"github.com/kalverra/octometrics/gather"
	"github.com/kalverra/octometrics/observe"
	"github.com/rs/zerolog"
	mock "github.com/stretchr/testify/mock"
)

// NewMockObserver creates a new instance of MockObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObserver {
	mock := &MockObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObserver is an autogenerated mock type for the Observer type
type MockObserver struct {
	mock.Mock
}

type MockObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObserver) EXPECT() *MockObserver_Expecter {
	return &MockObserver_Expecter{mock: &_m.Mock}
}

// CompareWorkflowRuns provides a mock function for the type MockObserver
func (_mock *MockObserver) CompareWorkflowRuns(log zerolog.Logger, client *gather.GitHubClient, owner string, repo string, leftID int64, rightID int64, opts ...observe.Option) (*observe.Comparison, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(log, client, owner, repo, leftID, rightID, opts)
	} else {
		tmpRet = _mock.Called(log, client, owner, repo, leftID, rightID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CompareWorkflowRuns")
	}

	var r0 *observe.Comparison
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(zerolog.Logger, *gather.GitHubClient, string, string, int64, int64, ...observe.Option) (*observe.Comparison, error)); ok {
		return returnFunc(log, client, owner, repo, leftID, rightID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(zerolog.Logger, *gather.GitHubClient, string, string, int64, int64, ...observe.Option) *observe.Comparison); ok {
		r0 = returnFunc(log, client, owner, repo, leftID, rightID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*observe.Comparison)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(zerolog.Logger, *gather.GitHubClient, string, string, int64, int64, ...observe.Option) error); ok {
		r1 = returnFunc(log, client, owner, repo, leftID, rightID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObserver_CompareWorkflowRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompareWorkflowRuns'
type MockObserver_CompareWorkflowRuns_Call struct {
	*mock.Call
}

// CompareWorkflowRuns is a helper method to define mock.On call
//   - log zerolog.Logger
//   - client *gather.GitHubClient
//   - owner string
//   - repo string
//   - leftID int64
//   - rightID int64
//   - opts ...observe.Option
func (_e *MockObserver_Expecter) CompareWorkflowRuns(log interface{}, client interface{}, owner interface{}, repo interface{}, leftID interface{}, rightID interface{}, opts ...interface{}) *MockObserver_CompareWorkflowRuns_Call {
	return &MockObserver_CompareWorkflowRuns_Call{Call: _e.mock.On("CompareWorkflowRuns",
		append([]interface{}{log, client, owner, repo, leftID, rightID}, opts...)...)}
}

func (_c *MockObserver_CompareWorkflowRuns_Call) Run(run func(log zerolog.Logger, client *gather.GitHubClient, owner string, repo string, leftID int64, rightID int64, opts ...observe.Option)) *MockObserver_CompareWorkflowRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 zerolog.Logger
		if args[0] != nil {
			arg0 = args[0].(zerolog.Logger)
		}
		var arg1 *gather.GitHubClient
		if args[1] != nil {
			arg1 = args[1].(*gather.GitHubClient)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		var arg6 []observe.Option
		var variadicArgs []observe.Option
		if len(args) > 6 {
			variadicArgs = args[6].([]observe.Option)
		}
		arg6 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6...,
		)
	})
	return _c
}

func (_c *MockObserver_CompareWorkflowRuns_Call) Return(comparison *observe.Comparison, err error) *MockObserver_CompareWorkflowRuns_Call {
	_c.Call.Return(comparison, err)
	return _c
}

func (_c *MockObserver_CompareWorkflowRuns_Call) RunAndReturn(run func(log zerolog.Logger, client *gather.GitHubClient, owner string, repo string, leftID int64, rightID int64, opts ...observe.Option) (*observe.Comparison, error)) *MockObserver_CompareWorkflowRuns_Call {
	_c.Call.Return(run)
	return _c
}

// JobRuns provides a mock function for the type MockObserver
func (_mock *MockObserver) JobRuns(log zerolog.Logger, client *gather.GitHubClient, owner string, repo string, runID int64, opts ...observe.Option) ([]*observe.Observation, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(log, client, owner, repo, runID, opts)
	} else {
		tmpRet = _mock.Called(log, client, owner, repo, runID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JobRuns")
	}

	var r0 []*observe.Observation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(zerolog.Logger, *gather.GitHubClient, string, string, int64, ...observe.Option) ([]*observe.Observation, error)); ok {
		return returnFunc(log, client, owner, repo, runID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(zerolog.Logger, *gather.GitHubClient, string, string, int64, ...observe.Option) []*observe.Observation); ok {
		r0 = returnFunc(log, client, owner, repo, runID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*observe.Observation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(zerolog.Logger, *gather.GitHubClient, string, string, int64, ...observe.Option) error); ok {
		r1 = returnFunc(log, client, owner, repo, runID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObserver_JobRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobRuns'
type MockObserver_JobRuns_Call struct {
	*mock.Call
}

// JobRuns is a helper method to define mock.On call
//   - log zerolog.Logger
//   - client *gather.GitHubClient
//   - owner string
//   - repo string
//   - runID int64
//   - opts ...observe.Option
func (_e *MockObserver_Expecter) JobRuns(log interface{}, client interface{}, owner interface{}, repo interface{}, runID interface{}, opts ...interface{}) *MockObserver_JobRuns_Call {
	return &MockObserver_JobRuns_Call{Call: _e.mock.On("JobRuns",
		append([]interface{}{log, client, owner, repo, runID}, opts...)...)}
}

func (_c *MockObserver_JobRuns_Call) Run(run func(log zerolog.Logger, client *gather.GitHubClient, owner string, repo string, runID int64, opts ...observe.Option)) *MockObserver_JobRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 zerolog.Logger
		if args[0] != nil {
			arg0 = args[0].(zerolog.Logger)
		}
		var arg1 *gather.GitHubClient
		if args[1] != nil {
			arg1 = args[1].(*gather.GitHubClient)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 []observe.Option
		var variadicArgs []observe.Option
		if len(args) > 5 {
			variadicArgs = args[5].([]observe.Option)
		}
		arg5 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5...,
		)
	})
	return _c
}

func (_c *MockObserver_JobRuns_Call) Return(observations []*observe.Observation, err error) *MockObserver_JobRuns_Call {
	_c.Call.Return(observations, err)
	return _c
}

func (_c *MockObserver_JobRuns_Call) RunAndReturn(run func(log zerolog.Logger, client *gather.GitHubClient, owner string, repo string, runID int64, opts ...observe.Option) ([]*observe.Observation, error)) *MockObserver_JobRuns_Call {
	_c.Call.Return(run)
	return _c
}

// WorkflowRun provides a mock function for the type MockObserver
func (_mock *MockObserver) WorkflowRun(log zerolog.Logger, client *gather.GitHubClient, owner string, repo string, runID int64, opts ...observe.Option) (*observe.Observation, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(log, client, owner, repo, runID, opts)
	} else {
		tmpRet = _mock.Called(log, client, owner, repo, runID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for WorkflowRun")
	}

	var r0 *observe.Observation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(zerolog.Logger, *gather.GitHubClient, string, string, int64, ...observe.Option) (*observe.Observation, error)); ok {
		return returnFunc(log, client, owner, repo, runID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(zerolog.Logger, *gather.GitHubClient, string, string, int64, ...observe.Option) *observe.Observation); ok {
		r0 = returnFunc(log, client, owner, repo, runID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*observe.Observation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(zerolog.Logger, *gather.GitHubClient, string, string, int64, ...observe.Option) error); ok {
		r1 = returnFunc(log, client, owner, repo, runID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObserver_WorkflowRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkflowRun'
type MockObserver_WorkflowRun_Call struct {
	*mock.Call
}

// WorkflowRun is a helper method to define mock.On call
//   - log zerolog.Logger
//   - client *gather.GitHubClient
//   - owner string
//   - repo string
//   - runID int64
//   - opts ...observe.Option
func (_e *MockObserver_Expecter) WorkflowRun(log interface{}, client interface{}, owner interface{}, repo interface{}, runID interface{}, opts ...interface{}) *MockObserver_WorkflowRun_Call {
	return &MockObserver_WorkflowRun_Call{Call: _e.mock.On("WorkflowRun",
		append([]interface{}{log, client, owner, repo, runID}, opts...)...)}
}

func (_c *MockObserver_WorkflowRun_Call) Run(run func(log zerolog.Logger, client *gather.GitHubClient, owner string, repo string, runID int64, opts ...observe.Option)) *MockObserver_WorkflowRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 zerolog.Logger
		if args[0] != nil {
			arg0 = args[0].(zerolog.Logger)
		}
		var arg1 *gather.GitHubClient
		if args[1] != nil {
			arg1 = args[1].(*gather.GitHubClient)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 []observe.Option
		var variadicArgs []observe.Option
		if len(args) > 5 {
			variadicArgs = args[5].([]observe.Option)
		}
		arg5 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5...,
		)
	})
	return _c
}

func (_c *MockObserver_WorkflowRun_Call) Return(observation *observe.Observation, err error) *MockObserver_WorkflowRun_Call {
	_c.Call.Return(observation, err)
	return _c
}

func (_c *MockObserver_WorkflowRun_Call) RunAndReturn(run func(log zerolog.Logger, client *gather.GitHubClient, owner string, repo string, runID int64, opts ...observe.Option) (*observe.Observation, error)) *MockObserver_WorkflowRun_Call {
	_c.Call.Return(run)
	return _c
}
