// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gather

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProgressReporter creates a new instance of MockProgressReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProgressReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProgressReporter {
	mock := &MockProgressReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProgressReporter is an autogenerated mock type for the ProgressReporter type
type MockProgressReporter struct {
	mock.Mock
}

type MockProgressReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProgressReporter) EXPECT() *MockProgressReporter_Expecter {
	return &MockProgressReporter_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockProgressReporter
func (_mock *MockProgressReporter) Start(msg string) {
	_mock.Called(msg)
	return
}

// MockProgressReporter_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockProgressReporter_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - msg string
func (_e *MockProgressReporter_Expecter) Start(msg interface{}) *MockProgressReporter_Start_Call {
	return &MockProgressReporter_Start_Call{Call: _e.mock.On("Start", msg)}
}

func (_c *MockProgressReporter_Start_Call) Run(run func(msg string)) *MockProgressReporter_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProgressReporter_Start_Call) Return() *MockProgressReporter_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProgressReporter_Start_Call) RunAndReturn(run func(msg string)) *MockProgressReporter_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockProgressReporter
func (_mock *MockProgressReporter) Stop(msg string) {
	_mock.Called(msg)
	return
}

// MockProgressReporter_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockProgressReporter_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - msg string
func (_e *MockProgressReporter_Expecter) Stop(msg interface{}) *MockProgressReporter_Stop_Call {
	return &MockProgressReporter_Stop_Call{Call: _e.mock.On("Stop", msg)}
}

func (_c *MockProgressReporter_Stop_Call) Run(run func(msg string)) *MockProgressReporter_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProgressReporter_Stop_Call) Return() *MockProgressReporter_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProgressReporter_Stop_Call) RunAndReturn(run func(msg string)) *MockProgressReporter_Stop_Call {
	_c.Run(run)
	return _c
}

// Update provides a mock function for the type MockProgressReporter
func (_mock *MockProgressReporter) Update(msg string, elapsed time.Duration) {
	_mock.Called(msg, elapsed)
	return
}

// MockProgressReporter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProgressReporter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - msg string
//   - elapsed time.Duration
func (_e *MockProgressReporter_Expecter) Update(msg interface{}, elapsed interface{}) *MockProgressReporter_Update_Call {
	return &MockProgressReporter_Update_Call{Call: _e.mock.On("Update", msg, elapsed)}
}

func (_c *MockProgressReporter_Update_Call) Run(run func(msg string, elapsed time.Duration)) *MockProgressReporter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProgressReporter_Update_Call) Return() *MockProgressReporter_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProgressReporter_Update_Call) RunAndReturn(run func(msg string, elapsed time.Duration)) *MockProgressReporter_Update_Call {
	_c.Run(run)
	return _c
}
