name: Build, Lint, and Test
on:
    push:
        branches:
          - main
        tags:
          - '*'
    pull_request:
        branches:
          - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Set up Go
            uses: actions/setup-go@v5
            with:
              go-version: stable
          - name: Install Dependencies
            run: go mod download
          - name: Build Octometrics
            run: go build -o octometrics-binary .
          - name: Upload binary
            uses: actions/upload-artifact@v4
            with:
              name: octometrics-binary
              path: octometrics-binary
              retention-days: 1
              if-no-files-found: error

    test:
        name: Test
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: Download Built Binary
            uses: actions/download-artifact@v4
            with:
              name: octometrics-binary
              path: .
          - name: Monitor
            uses: kalverra/octometrics-action@v0.0.5
            with:
              job_name: Test
              version: ./octometrics-binary
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Setup Go
            uses: actions/setup-go@v5
            with:
              go-version: stable
          - name: Install Dependencies
            run: go mod download
          - name: Run tests
            run: OCTOMETRICS_TEST_LOG_LEVEL=trace go tool gotestsum --junitfile junit.xml -- -coverprofile=cover.out ./...
          - name: Upload coverage reports to Codecov
            uses: codecov/codecov-action@v5
            with:
              token: ${{ secrets.CODECOV_TOKEN }}
              files: cover.out
          - name: Upload test results to Codecov
            if: ${{ !cancelled() }}
            uses: codecov/test-results-action@v1
            with:
              token: ${{ secrets.CODECOV_TOKEN }}

    test-race:
        name: Test (Race)
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: Download Built Binary
            uses: actions/download-artifact@v4
            with:
              name: octometrics-binary
              path: .
          - name: Monitor
            uses: kalverra/octometrics-action@v0.0.5
            with:
              job_name: Test (Race)
              version: ./octometrics-binary
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Setup Go
            uses: actions/setup-go@v5
            with:
              go-version: stable
          - name: Install Dependencies
            run: go mod download
          - name: Run tests with race detector
            run: OCTOMETRICS_TEST_LOG_LEVEL=trace go tool gotestsum -- -count=1 -cover -race ./...

    lint:
        name: Lint
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: Download Built Binary
            uses: actions/download-artifact@v4
            with:
              name: octometrics-binary
              path: .
          - name: Monitor
            uses: kalverra/octometrics-action@v0.0.5
            with:
              job_name: Lint
              version: ./octometrics-binary
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Set up Go
            uses: actions/setup-go@v5
            with:
              go-version: stable
          - name: Install Dependencies
            run: go mod download
          - name: golangci-lint
            uses: golangci/golangci-lint-action@v7
            with:
              version: v2.0
