name: Lint and Test
on:
    push:
        branches:
          - main
        tags:
          - '*'
    pull_request:
        branches:
          - main

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Monitor
              uses: kalverra/octometrics-action@main
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: stable
            - name: Install Dependencies
              run: go mod download
            - name: Install gotestsum
              run: go install gotest.tools/gotestsum@latest
            - name: Run tests
              run: OCTOMETRICS_TEST_LOG_LEVEL=trace gotestsum --junitfile junit.xml -- -coverprofile=cover.out ./...
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                files: cover.out
            - name: Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@v1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}

    test-race:
        name: Test (Race)
        runs-on: ubuntu-latest
        steps:
            - name: Monitor
              uses: kalverra/octometrics-action@main
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: stable
            - name: Install Dependencies
              run: go mod download
            - name: Install gotestsum
              run: go install gotest.tools/gotestsum@latest
            - name: Run tests with race detector
              run: OCTOMETRICS_TEST_LOG_LEVEL=trace gotestsum -- -cover -race ./...

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Monitor
              uses: kalverra/octometrics-action@main
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: stable
            - name: Install Dependencies
              run: go mod download
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v7
              with:
                version: v2.0
