name: Lint and Test
on:
    push:
        branches:
          - main
        tags:
          - 'v*.*.*'
    pull_request:
        branches:
          - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: 1.24.1
            - name: Install Dependencies
              run: go mod download
            - name: Set up gotestfmt
              uses: GoTestTools/gotestfmt-action@v2
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Run tests
              run: |
                  set -euo pipefail
                  go test -json -cover -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
            - name: Upload Test Results to Trunk.io
              if: ${{ !cancelled() }}
              uses: trunk-io/analytics-uploader@main
              with:
                junit-paths: "**/junit.xml"
                org-slug: adam-test
                token: ${{ secrets.TRUNK_TOKEN }}
